# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      # Install poetry
      - pip install poetry
    post_install:
      # Install project with dev dependencies using poetry
      # Note: sphinx-autodoc-typehints removed from dependencies - using built-in sphinx.ext.autodoc.typehints instead
      - poetry config virtualenvs.create false
      - poetry install --with dev --no-interaction --no-ansi

sphinx:
  configuration: docs_api/source/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
